### ISSUE TITLE
program crashed on version tableauhyperapi-0.0.18825 and above  in windows 7 

### ISSUE THREAD

**Issue by l1t1** [tableau/hyper-db#116]
I used the example of document
```
D:\>type pantab2.txt
import pandas as pd
import pantab as pt

df = pd.DataFrame([
    ["dog", 4],
    ["cat", 4],
], columns=["animal", "num_of_legs"])

pt.frame_to_hyper(df, "example.hyper", table="animals")
```
if i install tableauhyperapi-0.0.18825
```
D:\>pip install tableauhyperapi-0.0.18825-py3-none-win_amd64.whl
Looking in indexes: https://pypi.tuna.tsinghua.edu.cn/simple
Processing d:\tableauhyperapi-0.0.18825-py3-none-win_amd64.whl
Requirement already satisfied: cffi!=1.14.3,<2,>=1.12.2 in d:\python38\lib\site-packages (from tableauhyperapi==0.0.18825) (1.14.6)
Requirement already satisfied: pycparser in d:\python38\lib\site-packages (from cffi!=1.14.3,<2,>=1.12.2->tableauhyperapi==0.0.18825) (2.20)
Installing collected packages: tableauhyperapi
  Attempting uninstall: tableauhyperapi
    Found existing installation: tableauhyperapi 0.0.19691
    Uninstalling tableauhyperapi-0.0.19691:
      Successfully uninstalled tableauhyperapi-0.0.19691
Successfully installed tableauhyperapi-0.0.18825

D:\>python pantab2.txt
tableauhyperapi.hyperexception.HyperException: The Hyper server process exited during startup with exit code: -1073741511
        Command-line: ""D:\Python38\lib\site-packages\tableauhyperapi\bin\hyper\hyperd.exe" "run" "--date-style=MDY" "--date-style-lenient=false" "--init-user=tableau_internal_user" "--language=en_US" "--log-config=file,json,all,hyperd,0
"--log-dir=D:\\" "--no-password=true" "--skip-license=true" "--listen-connection" "tab.pipe://./pipe/auto" "--callback-connection" "tab.pipe://./pipe/{08E1C950-01C2-4C71-B337-5B527D1B4453}" "

        Check the hyperd log for more information

Context: 0x13cead20

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "pantab2.txt", line 2, in <module>
    import pantab as pt
  File "D:\pantab.py", line 48, in <module>
    with HyperProcess(telemetry=Telemetry.DO_NOT_SEND_USAGE_DATA_TO_TABLEAU) as hyper:
  File "D:\Python38\lib\site-packages\tableauhyperapi\hyperprocess.py", line 80, in __init__
    Error.check(hapi.hyper_instance_create(InteropUtil.string_to_char_p(hyper_path),
  File "D:\Python38\lib\site-packages\tableauhyperapi\impl\dllutil.py", line 100, in check
    raise errp.to_exception()
tableauhyperapi.hyperexception.HyperException: Failed to start a new Hyper instance.
Context: 0x86a93465

Caused by:
The Hyper server process exited during startup with exit code: -1073741511
        Command-line: ""D:\Python38\lib\site-packages\tableauhyperapi\bin\hyper\hyperd.exe" "run" "--date-style=MDY" "--date-style-lenient=false" "--init-user=tableau_internal_user" "--language=en_US" "--log-config=file,json,all,hyperd,0
"--log-dir=D:\\" "--no-password=true" "--skip-license=true" "--listen-connection" "tab.pipe://./pipe/auto" "--callback-connection" "tab.pipe://./pipe/{08E1C950-01C2-4C71-B337-5B527D1B4453}" "

        Check the hyperd log for more information

Context: 0x13cead20
```
downgrade to 0.0.18618, the program reports other errors
```
D:\>pip install tableauhyperapi-0.0.18618-py3-none-win_amd64.whl
Looking in indexes: https://pypi.tuna.tsinghua.edu.cn/simple
Processing d:\tableauhyperapi-0.0.18618-py3-none-win_amd64.whl
Requirement already satisfied: cffi!=1.14.3,<2,>=1.12.2 in d:\python38\lib\site-packages (from tableauhyperapi==0.0.18618) (1.14.6)
Requirement already satisfied: pycparser in d:\python38\lib\site-packages (from cffi!=1.14.3,<2,>=1.12.2->tableauhyperapi==0.0.18618) (2.20)
Installing collected packages: tableauhyperapi
  Attempting uninstall: tableauhyperapi
    Found existing installation: tableauhyperapi 0.0.18825
    Uninstalling tableauhyperapi-0.0.18825:
      Successfully uninstalled tableauhyperapi-0.0.18825
Successfully installed tableauhyperapi-0.0.18618

D:\>python pantab2.txt
Traceback (most recent call last):
  File "pantab2.txt", line 2, in <module>
    import pantab as pt
  File "D:\pantab.py", line 50, in <module>
    func(hyper, n)
TypeError: write_via_pantab() takes 1 positional argument but 2 were given

```

**Comment by l1t1** [comment]
I notice the error message
```
The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "pantab2.txt", line 2, in <module>
    import pantab as pt
  File "D:\pantab.py", line 48, in <module>
```
and delete the file d:\pantab.py, it now reports
```
D:\>python pantab2.txt
RuntimeError: module compiled against API version 0x10 but this version of numpy is 0xe . Check the section C-API incompatibility at the Troubleshooting ImportError section at https://numpy.org/devdocs/user/troubleshooting-importerror.htm
#c-api-incompatibility for indications on how to solve this problem .
Traceback (most recent call last):
  File "pantab2.txt", line 2, in <module>
    import pantab as pt
  File "D:\Python38\lib\site-packages\pantab\__init__.py", line 3, in <module>
    import libpantab  # type: ignore
ImportError: numpy.core.multiarray failed to import
```
