### ISSUE TITLE
the API cannot run on python 3.12  on windows 10 with an old CPU(intel core 2 duo P8700)

### ISSUE THREAD

**Issue by l1t1** [tableau/hyper-db#122]
```
D:\>pip install tableauhyperapi
Looking in indexes: https://pypi.tuna.tsinghua.edu.cn/simple
Collecting tableauhyperapi
  Downloading https://pypi.tuna.tsinghua.edu.cn/packages/83/d4/007c1d731e3550c63dc4e61e6e99f81650845a7fb19571dda0a28c28915b/tableauhyperapi-0.0.20027-py3-none-win_amd64.whl (54.8 MB)
     ---------------------------------------- 54.8/54.8 MB 3.0 MB/s eta 0:00:00
Collecting cffi!=1.14.3,<2,>=1.12.2 (from tableauhyperapi)
  Downloading https://pypi.tuna.tsinghua.edu.cn/packages/72/21/8c5d285fe20a6e31d29325f1287bb0e55f7d93630a5a44cafdafb5922495/cffi-1.17.0-cp312-cp312-win_amd64.whl (181 kB)
     ---------------------------------------- 181.5/181.5 kB 475.7 kB/s eta 0:00:00
Collecting pycparser (from cffi!=1.14.3,<2,>=1.12.2->tableauhyperapi)
  Downloading https://pypi.tuna.tsinghua.edu.cn/packages/13/a3/a812df4e2dd5696d1f351d58b8fe16a405b234ad2886a0dab9183fb78109/pycparser-2.22-py3-none-any.whl (117 kB)
     ---------------------------------------- 117.6/117.6 kB 683.5 kB/s eta 0:00:00
Installing collected packages: pycparser, cffi, tableauhyperapi
Successfully installed cffi-1.17.0 pycparser-2.22 tableauhyperapi-0.0.20027

[notice] A new release of pip is available: 24.0 -> 24.2
[notice] To update, run: python.exe -m pip install --upgrade pip

D:\>python
Python 3.12.2 (tags/v3.12.2:6abddd9, Feb  6 2024, 21:26:36) [MSC v.1937 64 bit (AMD64)] on win32
Type "help", "copyright", "credits" or "license" for more information.


>>> import tableauhyperapi
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "D:\Python312\Lib\site-packages\tableauhyperapi\__init__.py", line 116, in <module>
    from .catalog import Catalog
  File "D:\Python312\Lib\site-packages\tableauhyperapi\catalog.py", line 4, in <module>
    from .connection import Connection
  File "D:\Python312\Lib\site-packages\tableauhyperapi\connection.py", line 11, in <module>
    from .result import Result
  File "D:\Python312\Lib\site-packages\tableauhyperapi\result.py", line 8, in <module>
    from .date import Date
  File "D:\Python312\Lib\site-packages\tableauhyperapi\date.py", line 4, in <module>
    from .impl import hapi
  File "D:\Python312\Lib\site-packages\tableauhyperapi\impl\hapi.py", line 4, in <module>
    from .dll import lib
  File "D:\Python312\Lib\site-packages\tableauhyperapi\impl\dll.py", line 18, in <module>
    lib = ffi.dlopen(str(find_hyper_api_library()))
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
OSError: cannot load library 'D:\Python312\Lib\site-packages\tableauhyperapi\bin\tableauhyperapi.dll': error 0x45a
		
```

**Comment by l1t1** [comment]
an old version output clearer message
```python
pip install tableauhyperapi==0.0.12005

>>> from tableauhyperapi import HyperProcess, Connection, Telemetry, CreateMode
>>> with HyperProcess(Telemetry.SEND_USAGE_DATA_TO_TABLEAU,
...             parameters = {"default_database_version": "2"}) as hyper:
...     with Connection(hyper.endpoint, 'TrivialExample.hyper', CreateMode.CREATE_AND_REPLACE) as connection:
...         # Create an `Extract` table inside an `Extract` schema
...         connection.catalog.create_schema('Extract')
...         example_table = TableDefinition(TableName('Extract','Extract'), [
...             TableDefinition.Column('rowID', SqlType.big_int()),
...             TableDefinition.Column('value', SqlType.big_int()),
...         ])
...         connection.catalog.create_table(example_table)
...
tableauhyperapi.hyperexception.HyperException: The Hyper API requires a processor that supports SSE4.2, SSE4.1, SSSE3, SSE3 and POPCNT instructions.
Context: 0xf4c5532

```
